# @package _global_

image:
  expected_size: [320, 240]
  normalize: true
  resize: true

sync:
  block_timeout: 100.0
  check_interval: 0.01
  timestamp_tolerance: 0.0015
  sync_target: image

safety:
  action_delta_threshold: 0.1
